16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/frontends/views.py
"""
"""
from flask import (Blueprint, request, render_template, flash,
    g, session, redirect, url_for)
from werkzeug.security import check_password_hash, generate_password_hash

from flask_reddit import db
from flask_reddit import search as search_module # don't override function name
from flask_reddit.users.forms import RegisterForm, LoginForm
from flask_reddit.users.models import User
from flask_reddit.threads.models import Thread
from flask_reddit.subreddits.models import Subreddit
from flask_reddit.users.decorators import requires_login

mod = Blueprint('frontends', __name__, url_prefix='')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

def home_subreddit():
    return Subreddit.query.get_or_404(1)

def get_subreddits():
    """
    important and widely imported method because a list of
    the top 30 subreddits are present on every page in the sidebar
    """
    subreddits = Subreddit.query.filter(Subreddit.id != 1)[:25]
    return subreddits

def process_thread_paginator(trending=False, rs=None, subreddit=None):
    """
    abstracted because many sources pull from a thread listing
    source (subreddit permalink, homepage, etc)
    """
    threads_per_page = 15
    cur_page = request.args.get('page') or 1
    cur_page = int(cur_page)
    thread_paginator = None

    # if we are passing in a resultset, that means we are just looking to
    # quickly paginate some arbitrary data, no sorting
    if rs:
        thread_paginator = rs.paginate(cur_page, per_page=threads_per_page,
            error_out=True)
        return thread_paginator

    # sexy line of code :)
    base_query = subreddit.threads if subreddit else Thread.query

    if trending:
        thread_paginator = base_query.order_by(db.desc(Thread.votes)).\
        paginate(cur_page, per_page=threads_per_page, error_out=True)
    else:
        thread_paginator = base_query.order_by(db.desc(Thread.hotness)).\
                paginate(cur_page, per_page=threads_per_page, error_out=True)
    return thread_paginator

#@mod.route('/<regex("trending"):trending>/')
@mod.route('/')
def home(trending=False):
    """
    If not trending we order by creation date
    """
    trending = True if request.args.get('trending') else False
    subreddits = get_subreddits()
    thread_paginator = process_thread_paginator(trending)

    return render_template('home.html', user=g.user,
            subreddits=subreddits, cur_subreddit=home_subreddit(),
            thread_paginator=thread_paginator)

@mod.route('/search/', methods=['GET'])
def search():
    """
    Allows users to search threads and comments
    """
    query = request.args.get('query')
    rs = search_module.search(query, orderby='creation', search_title=True,
            search_text=True, limit=100)

    thread_paginator = process_thread_paginator(rs=rs)
    rs = rs.all()
    num_searches = len(rs)
    subreddits = get_subreddits()

    return render_template('home.html', user=g.user,
            subreddits=subreddits, cur_subreddit=home_subreddit(),
            thread_paginator=thread_paginator, num_searches=num_searches)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    We had to do some extra work to route the user back to
    his or her original place before logging in
    """
    if g.user:
        return redirect(url_for('frontends.home'))

    next = ''
    if request.method == 'GET':
        if 'next' in request.args:
            next = request.args['next']

    form = LoginForm(request.form)
    # make sure data is valid, but doesn't validate password is right
    if form.validate_on_submit():
        # continue where we left off if so
        user = User.query.filter_by(email=form.email.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['user_id'] = user.id

            if 'next' in request.form and request.form['next']:
                return redirect(request.form['next'])
            return redirect(url_for('frontends.home'))

        flash('Wrong email or password', 'danger')
    return render_template("login.html", form=form, next=next)

@mod.route('/logout/', methods=['GET', 'POST'])
@requires_login
def logout():
    session.pop('user_id', None)
    return redirect(url_for('frontends.home'))

@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    """
    next = ''
    if request.method == 'GET':
        if 'next' in request.args:
            next = request.args['next']

    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        user = User(username=form.username.data, email=form.email.data, \
                password=generate_password_hash(form.password.data))
        # Insert the record in our database and commit it
        db.session.add(user)
        db.session.commit()
        # Log the user in, as he now has an id
        session['user_id'] = user.id

        flash('thanks for signing up!', 'success')
        if 'next' in request.form and request.form['next']:
            return redirect(request.form['next'])
        return redirect(url_for('frontends.home'))

    return render_template("register.html", form=form, next=next)

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/subreddits/views.py
"""
"""
from flask import (Blueprint, request, render_template, flash, g,
        session, redirect, url_for, abort)
from flask_reddit.frontends.views import get_subreddits, process_thread_paginator
from flask_reddit.subreddits.forms import SubmitForm
from flask_reddit.subreddits.models import Subreddit
from flask_reddit.threads.models import Thread
from flask_reddit.users.models import User
from flask_reddit import db

mod = Blueprint('subreddits', __name__, url_prefix='/r')

#######################
### Subreddit Views ###
#######################

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

def meets_subreddit_criterea(subreddit):
    return True

@mod.route('/subreddits/submit/', methods=['GET', 'POST'])
def submit():
    """
    """
    if g.user is None:
        flash('You must be logged in to submit subreddits!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))

    form = SubmitForm(request.form)
    user_id = g.user.id

    if form.validate_on_submit():
        name = form.name.data.strip()
        desc = form.desc.data.strip()

        subreddit = Subreddit.query.filter_by(name=name).first()
        if subreddit:
            flash('subreddit already exists!', 'danger')
            return render_template('subreddits/submit.html', form=form, user=g.user,
                subreddits=get_subreddits())
        new_subreddit = Subreddit(name=name, desc=desc, admin_id=user_id)

        if not meets_subreddit_criterea(subreddit):
            return render_template('subreddits/submit.html', form=form, user=g.user,
                subreddits=get_subreddits())

        db.session.add(new_subreddit)
        db.session.commit()

        flash('Thanks for starting a community! Begin adding posts to your community\
                by clicking the red button to the right.', 'success')
        return redirect(url_for('subreddits.permalink', subreddit_name=new_subreddit.name))
    return render_template('subreddits/submit.html', form=form, user=g.user,
            subreddits=get_subreddits())

@mod.route('/delete/', methods=['GET', 'POST'])
def delete():
    """
    """
    pass

@mod.route('/subreddits/view_all/', methods=['GET'])
def view_all():
    """
    """
    return render_template('subreddits/all.html', user=g.user,
            subreddits=Subreddit.query.all())

@mod.route('/<subreddit_name>/', methods=['GET'])
def permalink(subreddit_name=""):
    """
    """
    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()
    if not subreddit:
        abort(404)

    trending = True if request.args.get('trending') else False
    thread_paginator = process_thread_paginator(trending=trending, subreddit=subreddit)
    subreddits = get_subreddits()

    return render_template('home.html', user=g.user, thread_paginator=thread_paginator,
        subreddits=subreddits, cur_subreddit=subreddit)

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/threads/views.py
"""
"""
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort)
from flask_reddit.threads.forms import SubmitForm
from flask_reddit.threads.models import Thread
from flask_reddit.users.models import User
from flask_reddit.subreddits.models import Subreddit
from flask_reddit.frontends.views import get_subreddits
from flask_reddit import db

mod = Blueprint('threads', __name__, url_prefix='/threads')

#######################
#### Threads Views ####
#######################

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

def meets_thread_criteria(thread):
    """
    """
    if not thread.title:
        flash('You must include a title!', 'danger')
        return False
    if not thread.text and not thread.link:
        flash('You must post either body text or a link!', 'danger')
        return False

    dup_link = Thread.query.filter_by(link=thread.link).first()
    if not thread.text and dup_link:
        flash('someone has already posted the same link as you!', 'danger')
        return False

    return True

@mod.route('/<subreddit_name>/submit/', methods=['GET', 'POST'])
def submit(subreddit_name=None):
    """
    """
    if g.user is None:
        flash('You must be logged in to submit posts!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))
    user_id = g.user.id

    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()
    if not subreddit:
        abort(404)

    form = SubmitForm(request.form)
    if form.validate_on_submit():
        title = form.title.data.strip()
        link = form.link.data.strip()
        text = form.text.data.strip()
        thread = Thread(title=title, link=link, text=text,
                user_id=user_id, subreddit_id=subreddit.id)

        if not meets_thread_criteria(thread):
            return render_template('threads/submit.html', form=form, user=g.user,
                cur_subreddit=subreddit.name)

        db.session.add(thread)
        db.session.commit()
        thread.set_hotness()

        flash('thanks for submitting!', 'success')
        return redirect(url_for('subreddits.permalink', subreddit_name=subreddit.name))
    return render_template('threads/submit.html', form=form, user=g.user,
            cur_subreddit=subreddit, subreddits=get_subreddits())

@mod.route('/delete/', methods=['GET', 'POST'])
def delete():
    """
    """
    pass

@mod.route('/edit/', methods=['GET', 'POST'])
def edit():
    """
    """
    pass

@mod.route('/<subreddit_name>/<thread_id>/<path:title>/', methods=['GET', 'POST'])
def thread_permalink(subreddit_name=None, thread_id=None, title=None):
    """
    """
    thread_id = thread_id or -99
    thread = Thread.query.get_or_404(int(thread_id))
    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()
    subreddits = get_subreddits()
    return render_template('threads/permalink.html', user=g.user, thread=thread,
            cur_subreddit=subreddit, subreddits=subreddits)

##########################
##### Comments Views #####
##########################

@mod.route('/comments/submit/', methods=['GET', 'POST'])
def submit_comment():
    """
    """
    pass

@mod.route('/comments/delete/', methods=['GET', 'POST'])
def delete_comment():
    """
    """
    pass

@mod.route('/comments/<comment_id>/', methods=['GET', 'POST'])
def comment_permalink():
    """
    """
    pass

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/users/views.py
"""
"""
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort)

from flask_reddit import db
from flask_reddit.users.models import User
from flask_reddit.frontends.views import get_subreddits
from flask_reddit.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

@mod.route('/<username>/')
def home_page(username=None):
    if not username:
        abort(404)
    user = User.query.filter_by(username=username).first()
    if not user:
        abort(404)
    return render_template('users/profile.html', user=g.user, current_user=user,
            subreddits = get_subreddits())

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="An extendable Reddit clone built with flask.">
    <title>{% block title %}Reddit clone built with flask, python, nginx, etc{% endblock %}</title>
    <meta name="keywords" content="flask,reddit,python,reddit-clone">

    <!-- Bootstrap core CSS -->
    <link rel="icon" href="{{ url_for('static', filename='imgs/favicon.ico') }}" type="image/x-icon">
    {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}

    <!-- Add custom CSS here -->
    <style>
        body {margin-top: 60px;}
    </style>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
              <li>
                  <a class="brand-nav" href="/">
                      {% if cur_subreddit is defined and cur_subreddit.id != 1 %}
                          {{ cur_subreddit.name }}
                      {% else %}
                          {{ config.BRAND }}
                      {% endif %}
                  </a>
              </li>
              <li>
                  <a href="/?trending=true">trending</a>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if user is not defined or user == None %}
              <li><a href="{{ url_for('frontends.register', next=request.path) }}">Register</a></li>
              <li><a href="{{ url_for('frontends.login', next=request.path) }}">Login</a></li>
          {% else %}
              <p class="navbar-text login-nav-text">logged in as
                  <a href="{{ url_for('users.home_page', username=user.username) }}">
                      {{ user.username }}</a>, &nbsp;
                  {{ user.get_thread_karma() }} <span class="karma-star">★</span>
              </p>
              <li class="logout-button"><a href="{{ config.ROOT_URL }}/logout">logout</a></li>
          {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div id="messages-wrap">
        <div id="messages">
          {% for category, msg in get_flashed_messages(with_categories=true) %}
          <div class="flash-{{ category }} alert alert-dismissable alert-{{ category }} flash-banner">
              {{ msg }}</p>
          {% endfor %}
        </div>
      </div>

      <div class="row main-box">
      {% block content %}

      {% endblock %}
      </div>

      <div class="row" class="" id="footer-row">
          <div class="col-lg-12">
          </div>
      </div>

    </div><!-- /.container -->

    <!-- Let's use a CDN -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    {% block scripts %}

    {% endblock %}
  </body>
</html>

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="col-lg-9 col-md-9 col-sm-7 col-xs-5 left-bar">
  {% block left %}
      {% if num_searches is defined %}
        <h4 class="highlight">We have found {{ num_searches }} search results </h4>
        <br>
      {% endif %}
      <div class="spacer"></div>
      {% for thread in thread_paginator.items %}
        <div name="{{ thread.id }}" class="row listing-row">
          <div class="col-lg-1 listing-vote-box">
              <div class="">
                  {% if user is defined and user != None and thread.has_voted(user.id) %}
                      <a data-voted="true" style="color:#eb6864;" href="javascript:void(0)"
                          class="listing-vote-button">▲</a>
                  {% else %}
                      <a data-voted="false" style="color:#000;" href="javascript:void(0)"
                          class="listing-vote-button">▲</a>
                  {% endif %}
              </div>
              <div class="listing-votes-number">
                  {{ thread.votes }}
              </div>
          </div>
          <div class="col-lg-1 listing-thumbnail-box">
              <img class="listing-image" src="{{ thread.thumbnail|replace("http://", "https://") }}"/>
          </div>
          <div class="col-lg-8 listing-text">
              {% if thread.link %}
              <a href="{{ thread.link }}" class="listing-title">
              {% else %}
              <a href="{{ config.ROOT_URL }}/threads/{{ thread.subreddit.name }}/{{ thread.id }}/{{ thread.title|truncate(100)|replace(' ', '_') }}" class="listing-title">
              {% endif %}
                <h4 class="listing-title-text">{{ thread.title }}</h4>
              </a>

              <div class="post-listing-meta">
                  <a href="{{ config.ROOT_URL }}/threads/{{ thread.subreddit.name }}/{{ thread.id }}/{{ thread.title|truncate(100)|replace(' ', '_') }}">
                  {{ thread.comments.all()|length() }} comments</a>,
                  {{ thread.pretty_date() }}, by
                  <a href="{{ url_for('users.home_page',
                        username=thread.user.username) }}">
                        {{ thread.user.username }}</a>
                    in
                    <a href="{{ url_for('subreddits.permalink',
                        subreddit_name=thread.subreddit.name) }}">
                        {{ thread.subreddit.name }}
                    </a>
              </div>
          </div>
        </div>
      {% endfor %}

      <ul class="pager pull-left">
        {% if thread_paginator.has_prev %}
            <li><a href="?page={{ thread_paginator.prev_num }}">prev</a></li>
        {% else %}
            <li style="opacity:0.3;"><a>prev</a></li>
        {% endif %}
        {% if thread_paginator.has_next %}
            <li><a href="?page={{ thread_paginator.next_num }}">next</a></li>
        {% else %}
            <li style="opacity:0.3;"><a>next</a></li>
        {% endif %}
      </ul>
  {% endblock %}
</div>

<div class="col-lg-3 right-bar">
  {% block right %}
    {% if user is defined and user != None %}
        <!-- -->
    {% else %}
        <!-- <h4 class="pre-reg-info">Please register or login to post!</h4>-->
    {% endif %}
    {% block create_buttons %}
    <div class="row">
        {% block user_dashboard %}
        {% endblock %}
        <form method="GET" action="/search/" class="" role="search">
            <div class="form-group">
                <input type="text" name="query" class="reddit-search form-control"
                    placeholder="Search reddit!">
            </div>
            <!--<button type="submit" class="btn btn-default">Submit</button>-->
        </form>
        {% if cur_subreddit is defined %}
            <a href="{{ url_for('threads.submit', subreddit_name=cur_subreddit.name) }}">
                <button class="btn btn-primary submit-post-button">
                    submit to {{ cur_subreddit.name }}</button>
            </a>
        {% else %}
            <a href="{{ url_for('threads.submit', subreddit_name='frontpage') }}">
                <button class="btn btn-primary submit-post-button">submit post</button></a>
        {% endif %}
        </div>
        <div class="row">
            <a href="{{ url_for('subreddits.submit') }}">
                <button type="button" class="btn btn-primary
            inverse-white-button add-subreddit-button">create community +</button></a>
    </div>

    {% if cur_subreddit is defined %}
    <p class="subreddit-desc">
        {{ cur_subreddit.desc }}
    </p>
    {% endif %}

    {% endblock %}

    <h4 class="subreddit-desc">Subreddits</h4>
    <ul id="subreddit-list">
        {% for subreddit in subreddits[:10] %}
        <li><a href="/r/{{ subreddit.name }}">{{ subreddit.name }}</a></li>
        {% endfor %}
    </ul>
    <a class="align-right-col" href="{{ url_for('subreddits.view_all') }}">view all</a>
    <i>
  {% endblock %}
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {
    $(document).on('click', 'a.listing-vote-button', function() {
        var $vote_button = $(this); // cache this! can't access in callback!
        var thread_id = $vote_button.parent().parent().parent().attr('name');
        var post_to = '/apis/threads/vote/';
        if ($vote_button.attr("data-voted") === "true") {
            $vote_button.css("color", "#000");
            $vote_button.attr("data-voted", "false");
        } else {
            $vote_button.css("color", "rgb(235, 104, 100)");
            $vote_button.attr("data-voted", "true");
        }
        {% if user is defined and user != None %}
            $.post(post_to, { thread_id: thread_id },
                function(response) {
                    var new_vote_count = response.new_votes.toString();
                    var vote_status = response.vote_status;
                    $vote_button.parent().parent().
                        children('div.listing-votes-number').html(new_vote_count);
                }, 'json'
            );
        {% else %}
            alert("You must be logged in to do that!");
        {% endif %}
    });
    //
    //
});
</script>
{% endblock %}

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title">Sign in to continue to Flask Reddit</h1>
            <div class="account-wall">
                <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                    alt="">
                {% from "macros.html" import render_field %}
                <form method="POST" action="." class="form-signin">
                {{ form.csrf_token }}
                <input type="hidden" name="next" value="{{ next }}"/>
                {{ render_field(form.email, class="form-control", 
                    placeholder="Email", autofocus="") }}
                {{ render_field(form.password, class="form-control", placeholder="Password") }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Sign in</button>
                <!--
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    Remember me
                </label>
                -->
                </form>
            </div>
            <a href="{{ url_for('frontends.register') }}" 
                class="text-center new-account">Create an account </a>
        </div>
    </div>
</div>
{% endblock %}

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/templates/macros.html
{% macro render_field(field) %}
  <div class="form_field">
  <!--{ field.label(class="label") }}-->
  {% if field.errors %}
    {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
    {{ field(class=css_class, **kwargs) }}
    <div class="alert alert-dismissable alert-danger">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
  {% else %}
    {{ field(**kwargs) }}
  {% endif %}
  </div>
{% endmacro %}

16_revisiting_relationships/01_many_to_many_and_joins/flask_reddit/templates/register.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
  <div class="col-lg-6" style="float: none; margin: 20px auto;">
  {% from "macros.html" import render_field %}
  <form method="POST" action="." class="form bs-example form-horizontal">
    {{ form.csrf_token }}
    <input type="hidden" name="next" value="{{ next }}" />
    {{ render_field(form.username, class="form-control", placeholder="username", autofocus="") }}
    <br>
    {{ render_field(form.email, class="form-control", placeholder="email") }}
    <br>
    {{ render_field(form.password, class="form-control", placeholder="password") }}
    <br>
    {{ render_field(form.confirm, class="form-control", placeholder="confirm password") }}
    <br>
    Check to agree to <a href="">terms of services</a> 
        {{ render_field(form.accept_tos, class="form-control") }}
    <button type="submit" value="Register" class="btn btn-primary">Register</button>
  </form>
  </div>
  </div>
{% endblock %}